baseurl                 = "www.erikvanek.com/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
title                   = "Hi, I'm Erik"
theme                   = "sam"
publishDir 		= "."
# googleAnalytics       = "UA-116349788-1"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/zen-circle.ico"
    pygmentsStyle       = "monokai"                     # https://help.farbox.com/pygments.html
    pygmentsCodefences  = true
#    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "img/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "Hi. I'm Erik. Sometimes I talk a lot."

# Metadata
    description         = "Hi. I'm Erik. I like to make stuff. Food, software, plants and many others."            # 
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/me"
    text = "who am I?"

[[params.mainMenu]]
    link = "/aero"
    text = "I like to grow plants"

[[params.mainMenu]]
    link = "/development"
    text = "develop on the web"

[[params.mainMenu]]
    link = "/commin-up"
    text = "but started elsewhere"
